require:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'notes.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/*'

RSpec/ExampleLength:
  Max: 15

Style/Documentation:
  Enabled: false
